name: 'Application pipeline'
description: 'Docker Build, GCP registry push and Kustomize step'

inputs:
  app-name:
    description: 'The app name'
    required: true
  gcp-registry-project-id:
    description: 'GCP Registry account project ID'
    required: true
  gcp-registry-service-account:
    description: 'GCP service account JSON to push images to registry'
    required: true
  github-actor:
    description: 'GH Actor'
    required: true
  github-deploy-ssh-key:
    description: 'The github deploy SSH key to clone K8S manifests'
    required: true
  github-package-url:
    description: 'The github package URL to download application packages'
    required: true
  github-token:
    description: 'The github token to create PR'
    required: true
  java-distribution:
    description: 'Java distribution name'
    required: true
  java-version:
    description: 'Java version'
    required: true
    default: 17
  k8s-manifest-repo-name:
    description: 'The name of K8S manifests repository'
    required: true
  k8s-manifest-repo-ssh:
    description: 'The SSH of K8S manifests repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get git repository informations
      uses: makevalue-tech/github-actions-git-informations@master

    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: 'Create settings.xml'
      uses: whelk-io/maven-settings-xml-action@v16
      with:
        repositories: |
          [
            {
              "id": "github",
              "url": "${{ inputs.github-package-url }}",
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: |
          [
            {
              "id": "github",
              "username": "${{ inputs.github-actor }}",
              "password": "${{ inputs.github-token }}"
            }
          ]

    - name: Set up JDK version
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: MVN Package
      shell: bash
      run: mvn -B package --file pom.xml -DskipTests

    - name: Push Image to GCR
      uses: RafikFarhad/push-to-gcr-github-action@v4.1.0
      with:
        gcloud_service_key: ${{ inputs.gcp-registry-service-account }}
        registry: gcr.io
        project_id: ${{ inputs.gcp-registry-project-id }}
        image_name: ${{ inputs.app-name }}
        image_tag: ${{ env.RELEASE_VERSION }}
        dockerfile: ./pipeline/Dockerfile

    - name: Kustomize step
      uses: makevalue-tech/github-actions-kustomize-argocd-manifests@master
      with:
        app-name: ${{ inputs.app-name }}
        app-registry: ${{ steps.login-ecr.outputs.registry }}
        github-actor: ${{ github.actor }}
        github-deploy-ssh-key: '${{ inputs.github-deploy-ssh-key }}'
        github-token: '${{ inputs.github-token }}'
        k8s-manifest-repo-name: '${{ inputs.k8s-manifest-repo-name }}'
        k8s-manifest-repo-ssh: '${{ inputs.k8s-manifest-repo-ssh }}'